[book]
title = "The Wolf Who Cried Wolf"
authors = ["Logan King👑"]
description = "How Good People Destroy Each Other in the Name of Safety. A framework for navigating mistakes, power, and repair in intimate spaces."
language = "en"

[build]
build-dir = "docs"

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/sloganking/sexy-minesweeper"
